//
// Created by Olcay Taner YILDIZ on 25.12.2025.
//

#ifndef COMPUTATIONALGRAPH_UNIFORMXAVIERINITIALIZATION_H
#define COMPUTATIONALGRAPH_UNIFORMXAVIERINITIALIZATION_H

double* uniform_xavier_initialization(int row, int column, unsigned seed);

#endif //COMPUTATIONALGRAPH_UNIFORMXAVIERINITIALIZATION_H